### ISSUE TITLE
How-To use this?

### ISSUE THREAD

**Issue by afahru** [EnesCakir/lynder#10]
Guys,

can you give me some example?

Thanks

**Comment by ZooShu** [comment]
`$ lynder

# Download a tutorial
$ lynder --url URL_OF_TUTORIAL
$ lynder -u URL_OF_TUTORIAL

# Download list of tutorials
# Links are seperated line by line in the txt
$ lynder --file list.txt
$ lynder -f list.txt

# Also you can use cookies for authentication
# It's faster than simple username and password
$ lynder -f list.txt -c cookies.txt`
