### ISSUE TITLE
enhancement:

### ISSUE THREAD

**Issue by gkochIT** [EnesCakir/lynder#8]
sometimes it happens that during downloads some files aren't downloaded or some files are missing. With youtuber-dl it is possible just to restart the download of the whole course and only the missing files will be added, existing files are skipped.

With lynder the script exists with an error when it can't create a folder at redownload. So it would be nice to work around this and make redownload possible with complete downloaded files being skipped.

**Comment by enescakir** [comment]
Fixed by @cmug81 on #12 PR 🎉
